Last3

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -51,7 +51,12 @@ jobs:
 
       - name: Install Argo CD CLI
         run: |
-          curl -sSL https://argoproj.github.io/argo-cd/keys/argocd.asc | gpg --dearmor -o /usr/share/keyrings/argocd-archive-keyring.gpg
+          if curl -sSL https://argoproj.github.io/argo-cd/keys/argocd.asc | gpg --dearmor -o /usr/share/keyrings/argocd-archive-keyring.gpg; then
+            echo "GPG key added successfully."
+          else
+            echo "Failed to add GPG key."
+            exit 1
+          fi
           echo "deb [signed-by=/usr/share/keyrings/argocd-archive-keyring.gpg] https://argoproj.github.io/argo-cd/apt/ stable main" | sudo tee /etc/apt/sources.list.d/argocd.list
           sudo apt-get update && sudo apt-get install argocd
 
