Last5

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -41,13 +41,27 @@ jobs:
         run: |
           docker build -t $DOCKER_IMAGE .
 
+      - name: Configure kubectl
+        run: |
+          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
+          kubectl --kubeconfig=kubeconfig.yaml get nodes
+
+      - name: Output kubeconfig content
+        run: cat kubeconfig.yaml
+
       - name: Install Argo CD CLI
         run: |
-          curl -sSL https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -o argocd
-          sudo install -m 755 argocd /usr/local/bin/argocd
+          if curl -sSL https://argoproj.github.io/argo-cd/keys/argocd.asc | gpg --dearmor -o /usr/share/keyrings/argocd-archive-keyring.gpg; then
+            echo "GPG key added successfully."
+          else
+            echo "Failed to add GPG key."
+            exit 1
+          fi
+          echo "deb [signed-by=/usr/share/keyrings/argocd-archive-keyring.gpg] https://argoproj.github.io/argo-cd/apt/ stable main" | sudo tee /etc/apt/sources.list.d/argocd.list
+          sudo apt-get update && sudo apt-get install argocd
 
       - name: Update Argo CD application
         run: |
-          argocd login a2448034a5e1f4ff796af814926572ff-1664569724.ap-northeast-1.elb.amazonaws.com --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --insecure
+          argocd login a2448034a5e1f4ff796af814926572ff-1664569724.ap-northeast-1.elb.amazonaws.com --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
           argocd app sync gu9duck-bank
           argocd app wait gu9duck-bank --timeout 150
